name: 🤖 Copilot Chat Validation & Guardrails

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  copilot-chat-validation:
    name: Copilot Chat Validation
    runs-on: ubuntu-latest

    steps:
      # --------------------------------------------------
      # Checkout
      # --------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # --------------------------------------------------
      # Validate Copilot Control Files
      # --------------------------------------------------
      - name: Validate Copilot Instruction Files
        run: |
          echo "🔍 Validating Copilot governance files..."
          test -f copilot-instructions.md || (echo "❌ copilot-instructions.md missing" && exit 1)
          test -f COPILOT_PROMPTS.md || (echo "❌ COPILOT_PROMPTS.md missing" && exit 1)
          echo "✅ Copilot governance files present"

      # --------------------------------------------------
      # Static Guardrail Checks
      # --------------------------------------------------
      - name: Scan for Forbidden Patterns
        run: |
          echo "🔍 Scanning codebase for forbidden patterns..."

          if grep -R "Thread.sleep" -n src; then
            echo "❌ Thread.sleep detected"
            exit 1
          fi

          if grep -R "MobileBy" -n src; then
            echo "❌ MobileBy detected – use AppiumBy"
            exit 1
          fi

          if grep -R "TODO" -n src; then
            echo "❌ TODO comments detected"
            exit 1
          fi

          if grep -R "FIXME" -n src; then
            echo "❌ FIXME comments detected"
            exit 1
          fi

          echo "✅ No forbidden patterns detected"

      # --------------------------------------------------
      # Validate Architecture Boundaries (Basic)
      # --------------------------------------------------
      - name: Validate Architecture Boundaries
        run: |
          echo "🔍 Validating architecture boundaries..."

          if grep -R "assertThat" src/main/java/com/company/qa/unified/pages; then
            echo "❌ Assertions detected inside Page Objects"
            exit 1
          fi

          if grep -R "RestAssured" src/test/java/com/company/qa/unified/pages; then
            echo "❌ API logic detected inside Page Objects"
            exit 1
          fi

          echo "✅ Architecture boundaries look clean"

      # --------------------------------------------------
      # Java Build Sanity Check
      # --------------------------------------------------
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Compile Project (Fail Fast)
        run: mvn -B -q clean compile

      # --------------------------------------------------
      # Smoke Confidence Check (API only)
      # --------------------------------------------------
      - name: Run Smoke Tests
        run: |
          mvn -B test \
            -Denv=qa \
            -Dplatform=api \
            -Dcucumber.filter.tags="@smoke"

      # --------------------------------------------------
      # PR Feedback
      # --------------------------------------------------
      - name: Comment on PR (Success)
        if: success() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `✅ **Copilot Chat Validation Passed**

  • Copilot governance files present
  • No forbidden patterns found
  • Architecture boundaries respected
  • Project compiles successfully
  • Smoke tests passed
  
  🚀 Safe to continue review / merge.`
  })

- name: Comment on PR (Failure)
  if: failure() && github.event_name == 'pull_request'
  uses: actions/github-script@v7
  with:
    script: |
      github.rest.issues.createComment({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        body: `❌ **Copilot Chat Validation Failed**

  One or more guardrails were violated.

Please check:
  • Forbidden patterns (Thread.sleep, MobileBy, TODO)
  • Architecture rules (assertions in Page Objects)
  • Compilation or smoke test failures
  
  Fix issues before requesting re-review.`
  })
